### ISSUE TITLE
errore importazione database

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/PriamiLeonardo#1]
Sto cercando di valutare il tuo progetto, ma non riesco ad importare il database.
Dopo circa 1 ora di lavoro, ottengo questo errore:

![image](https://user-images.githubusercontent.com/6524099/219066300-8a86838b-548f-4791-b1c6-597f959d2f82.png)

Nella console di Heidisql il messaggio è:

```
/* Errore SQL (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INSERT INTO rulings (uuid, date, text) VALUES ('85feac1f-31e0-5d87-a3ad-6ffad...' at line 1 */
/* File “AllPrintings.sql” eseguito, con 249.541 query e 249.529 righe interessate */
```

Come possiamo fare? ho importato con codifica UTF-8, forse il file ha una codifica diversa?

**Comment by leopriami** [comment]
Buonasera prof, ho appena provato a riscaricare il database e a importarlo nel mio ambiente di sviluppo con successo.
Io sto usando macOS Big Sur su un mac powerbook e uso MySQL Workbench per importare il db.
Ho usato il metodo Data Import/Restore dal tab Administration scegliendo l'opzione "Import from Self-Contained File" definendo lo schema mtg_cards con default charset e default collation e l'import termina correttamente in pochi minuti.
Grazie per avermi avvisato, mi faccia sapere

**Comment by fulcorno** [comment]
Proverò con MySQL workbench. È curioso che heidisql prevedesse 4 ore come tempo di importazione: avrò scaricato il file giusto?

**Comment by leopriami** [comment]
Il file da scaricare e' AllPrintings, dovrebbe essere l'unico a chiamarsi cosi'. Mi faccia sapere se riscontra problemi anche con MySQL workbench.
Buona giornata

**Comment by leopriami** [comment]
Buongiorno prof, e' riuscito ad importare il database? Nel caso ci fosse riuscito, le chiederei gentilmente se riesce a valutarmi entro il 2 marzo, che e' la data di scadenza per presentare la richiesta di laurea. Grazie e buona giornata

**Comment by fulcorno** [comment]
alla fine ci sono riuscito (dà comunque errore, ma i dati vengono caricati).
Ora ti registro i crediti.

**Comment by leopriami** [comment]
Grazie mille prof,
buona serata

Leonardo Priami

Il 2023-02-26 19:49 Fulvio Corno ha scritto:
